import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import { Container } from "@chakra-ui/react";
import Main from "../components/Layout/Main";
import Search from "../components/Search";
import Instagram from "../components/Instagram";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container maxW="container.md" align="center">
          <Main>
            <Header name={"Instagram Profile "} />
            <Search />
            <Instagram />
          </Main>
        </Container>
      </main>
    </div>
  );
}
